apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp1-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp1
  template:
    metadata:
      name: myapp1-pod
      labels:
        app: myapp1
    spec:
      containers:
        - name: myapp1-container
          image: 063965251904.dkr.ecr.us-east-1.amazonaws.com/nginx-app:92
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: myapp1-lb-service
spec:
  type: LoadBalancer
  selector:
    app: myapp1
  ports:
    - name: http
      port: 8080
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: myapp1-lb-service-nlb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  selector:
    app: myapp1
  ports:
    - name: http
      port: 8080
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: myapp1-nodeport-service
spec:
  type: NodePort
  selector:
    app: myapp1
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 31280
