name: Publish Docker image to ECR

on:
  push:
    branches: ["main"]

env:
  DOCKER_REGISTRY: ${{secrets.ECR_REPO_URL}}
  AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION}}
  APP_NAME: nginx-app
  AWS_ACCESS_KEY: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS: ${{secrets.AWS_SECRET_ACCESS_KEY}}

jobs:
  install-awcli-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install AWS CLI and Docker
        run: |
          sudo apt-get update
          sudo apt-get -y install awscli 
          sudo apt-get -y install curl
          curl -fsSL https://get.docker.com -o get-docker.sh
          chmod +x get-docker.sh
          ./get-docker.sh
  

  login-to-ecr-registry:
    needs: install-awcli-docker
    runs-on: ubuntu-latest
    steps:
      - name: Login to ECR registry
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION}}
        run: |
          aws ecr get-login-password --region ${{secrets.AWS_DEFAULT_REGION}} | docker login --username AWS --password-stdin ${{secrets.ECR_REPO_URL}}


  build-and-push-Docker-image-to-ECR:
    needs: [install-awcli-docker,login-to-ecr-registry]
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION}}
      DOCKER_REGISTRY: ${{secrets.ECR_REPO_URL}}
      APP_NAME: nginx-app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      

     

      - name: build_and_push
        run: |
          sudo docker build -t ${{env.DOCKER_REGISTRY}}/${{env.APP_NAME}}:${{ github.run_number }} .
          sudo docker push ${{env.DOCKER_REGISTRY}}/${{env.APP_NAME}}:${{ github.run_number }}
